---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stackdeployments.sandtech.io
  resources:
  - merndeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stackdeployments.sandtech.io
  resources:
  - merndeploys/finalizers
  verbs:
  - update
- apiGroups:
  - stackdeployments.sandtech.io
  resources:
  - merndeploys/status
  verbs:
  - get
  - patch
  - update
